import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def send_alert(recipient_email: str, report: dict) -> dict:
    """
    Sends an automated security alert email using SMTP.
    Returns a dict with 'status' and 'error' keys.
    """
    email_user = os.getenv("EMAIL_USER")
    email_pass = os.getenv("EMAIL_PASS")

    if not email_user or not email_pass:
        logger.warning("SMTP credentials not found in environment variables.")
        return {"status": "failed", "error": "SMTP credentials not configured."}

    subject = "⚠ Security Alert: Suspicious Email Detected"
    
    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <h2 style="color: #d9534f;">⚠ Security Alert: Suspicious/Phishing Email Detected</h2>
        <p>The CyberVerse AI Security Platform has analyzed a recent email or link and classified it as malicious.</p>
        
        <table style="border-collapse: collapse; width: 100%; max-width: 600px; margin-bottom: 20px;">
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Alert ID:</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{report.get('report_id', 'N/A')}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Risk Level:</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd; color: #d9534f; font-weight: bold;">{report.get('risk_level', 'HIGH')}</td>
            </tr>
            <tr style="background-color: #f9f9f9;">
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Confidence Score:</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{report.get('confidence', 0.95)}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;"><strong>Timestamp:</strong></td>
                <td style="padding: 10px; border: 1px solid #ddd;">{report.get('created_at', 'N/A')}</td>
            </tr>
        </table>
        
        <h3 style="color: #5bc0de;">Detection Reasons:</h3>
        <p>{report.get('summary', 'Unknown malicious activity detected.')}</p>
        
        <h3 style="color: #f0ad4e;">Recommended Actions:</h3>
        <ul>
            <li>Do <strong>not</strong> click any links.</li>
            <li>Do <strong>not</strong> download any attachments.</li>
            <li>Verify the sender's identity through alternate channels.</li>
            <li>Report the email to your Security Administrator immediately.</li>
        </ul>
        
        <br/>
        <p style="font-size: 12px; color: #777;">
            Automated Alert generated by CyberVerse AI Multi-Agent Platform.
        </p>
      </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = email_user
    msg['To'] = recipient_email
    msg['Subject'] = subject
    msg.attach(MIMEText(html_body, 'html'))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587, timeout=10)
        server.ehlo()
        server.starttls()
        server.login(email_user, email_pass)
        server.sendmail(email_user, recipient_email, msg.as_string())
        server.quit()
        logger.info(f"Successfully sent security alert email to {recipient_email}")
        return {"status": "success", "error": None}
    except Exception as e:
        error_msg = str(e)
        logger.error(f"Failed to send email to {recipient_email}: {error_msg}")
        return {"status": "failed", "error": error_msg}
